
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    fireBaseApi: 'https://bilel-daikhi-portfolio-default-rtdb.europe-west1.firebasedatabase.app',
    baseUrl:'${window.location.protocol}//${window.location.hostname}/portfolio/'
  };
