name: deploy portfolio to firebase

on: 
  push:
    branches:
       - master

jobs: 
  firebase-deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with: 
          node-version: "16.x" 

      - run: npm install --legacy-peer-deps 

      - run: |
          touch .env
          echo fireBaseApi=${{ secrets.FIREBASEAPI }} >> .env   
          echo API_KEY=${{ secrets.BASEURL }} >> .env

      - run: npm run build

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':elasticbeanstalk: :firebase: Deployment started... :grimacing: :crossed_fingers:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # NEW: set up service account credentials
      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase.json" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v15.10.0
        with: 
          args: deploy --only hosting

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
           text: ':tada: :arrow_right: https://bilel-daikhi-portfolio.web.app'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
